CREATE USER kafkademo identified BY ateamKafka#123;
grant CREATE session TO kafkademo;
grant RESOURCE TO kafkademo;
grant unlimited tablespace TO kafkademo;

CREATE TABLE kafkademo.TESTE
(
  ID NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  USERNAME VARCHAR2(50) NOT NULL,
  FIRST_NAME VARCHAR2(50) NOT NULL,
  MIDDLE_NAME VARCHAR2(50),
  LAST_NAME VARCHAR2(50) NOT NULL,
  AGE NUMBER(5,0) DEFAULT 0 NOT NULL,
  CREATED_ON TIMESTAMP(9) NOT NULL,
  CONSTRAINT TESTE_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);


INSERT INTO kafkademo.TESTE (username, first_name, middle_name, last_name, age, created_on) 
VALUES ('todd', 'Todd', null, 'Sharp', 42, sysdate);
INSERT INTO kafkademo.TESTE (username, first_name, middle_name, last_name, age, created_on) 
VALUES ('gvenzl', 'Gerald', null, 'Venzl', 30, sysdate);
INSERT INTO kafkademo.TESTE (username, first_name, middle_name, last_name, age, created_on) 
VALUES ('aalmiray', 'Andres', null, 'Almiray', 40, sysdate);
commit;